apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: log-generator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/afrociberdelio/log-generator.git"  # 游댳 Substitua pelo seu reposit칩rio
    targetRevision: main  # 游댳 Branch onde est치 o Helm Chart
    path: log-generator  # 游댳 Caminho dentro do reposit칩rio onde est치 o Chart
    helm:
      valueFiles:
        - values.yaml  # Usa o values.yaml padr칚o do chart
  destination:
    server: https://kubernetes.default.svc
    namespace: logging  # 游댳 Substitua pelo namespace onde deseja deployar
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # Cria o namespace caso n칚o exista
